name:                branch-prediction
version:             0.1.0.0
github:              "githubuser/branch-prediction"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/branch-prediction#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6
- extra >= 1.7

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - BPredictor.FST.GFST
    - BPredictor.FST.BP2FST
    - BPredictor.FST.PFST
    - BPredictor.FST.WFST
    - BPredictor.Nat
    - BPredictor.Utils

executables:
  branch-prediction-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - branch-prediction

tests:
  branch-prediction-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - branch-prediction
